### ISSUE TITLE
Trying to disconnect a Signal?

### ISSUE THREAD

**Issue by PhoenixWhitefire** [Hexcede/chlorine#9]
Hello, just stumbled upon this repository while looking around on H6x, wondering why it was archived, then checking your profile. I deduce the premise for this sandbox is that you are aiming to write a Luau parser from the ground-up instead of using `loadstring`?

Nonetheless, I was shamelessly copy-pasting the code when I got a warning in Studio for this little section in `Sandbox.lua` on line `158`:

```lua
elseif typeof(claimedValue) == "RBXScriptSignal" then
	claimedValue:Disconnect() --<-- HERE
end
```

It seems the intention was for it to check if `claimedValue` was an `RBXScriptConnection`, then `Disconnect` it if it was. I can't submit a PR because forking is busted right now for some reason, so I had to submit an Issue instead.

**Comment by Hexcede** [comment]
> Hello, just stumbled upon this repository while looking around on H6x, wondering why it was archived, then checking your profile. I deduce the premise for this sandbox is that you are aiming to write a Luau parser from the ground-up instead of using `loadstring`?

Nope, I mostly just wanted to start over, I didn't like how H6x was made. Chlorine is intended to work on any luau function, e.g. ideally you should be able to just as easily use a lua(u) in luau interpreter with Chlorine and still control the environment.

And yep, thanks for the catch.
